### PR TITLE
Fix icon color of RunWidget and background color of RecentProject of new UI

### PR DESCRIPTION
**Pull request by trofoto**
Fix icon color of RunWidget and background color of RecentProject of new UI, refer to `Light with Light Header theme`.
1. The icon color of RunWidge is too light to see;
2. The background color of RecentProject is too dark.

Just copied _RunWidget_ and _RecentProject_ in the theme file of `Light with Light Header theme`

### CODE REVIEW

**Comment by dinbtechit** [comment]
Thank you for an awesome PR mate! Are you able to post a before and after screenshots?

**Comment by trofoto** [comment]
> Thank you for an awesome PR mate! Are you able to post a before and after screenshots?

Sure.
1. Run widget color before:
a. nearly disappeared separator;
image
b. also disappeared running icon;
image
c. unsuitable hovered background color;
image
After patch:
image
image
image

2. Background color of RecentProject before:
Before:
Background color is too dark. So the colors between background and font are too close.
image
After patch:
image

Hope it helps.

**Comment by trofoto** [comment]
@dinbtechit Could you release 1.10.8 please, I'm really looking forward it. Thanks

**Comment by dinbtechit** [comment]
@trofoto—Apologies. I had to put this on the back burner. I was also a bit busy with my full-time job, and there are lots of deprecated API that need to be fixed to make it continue to support 2023.3 or higher which is basically blocking this.

I will try to get this out as soon as I can, hopefully by the end of this week. Thank you for your patience

**Pull request merged**
